### ISSUE TITLE
geth: Collect GC stats

### ISSUE THREAD

**Issue by chfast** [imapp-pl/gas-cost-estimator#123]
Using [`runtime.ReadMemStats`](https://pkg.go.dev/runtime#ReadMemStats) we can collect stats about memory allocations and GC in Go. This includes the pause time the GC caused to EVM execution.

I believe this should be done around `Execute()` in https://github.com/imapp-pl/gas-cost-estimator/blob/master/src/instrumentation_measurement/geth/main.go#L123.

If `total_time - gc_pause_time` is consistent, we can consider dropping `runtime.GC()`.

**Comment by pdobacz** [comment]
Thanks! Idea LGTM, with two modifications we discussed:
1. I'd rather watch `total_time / gc_pause_time`, to know if the GC cost is a "tax" with consistent (constant) rate
2. If it is, for all programs we handle, then we should rather **keep** `runtime.GC()`, arguing that the impact of GC is "fair" for all OPCODEs/programs, so we might as will measure with GC turned off

I'd also separate the versions of `geth` code which do `total_time` and `gc_pause_time` measurement.
